version: "3.8"
services:
   opskit-frontend:
     stdin_open: true
     container_name: opskit-frontend
     build:
       context: ./frontend/
       dockerfile: Dockerfile
     ports:
       - "3000:3000"
     volumes:
       - "./frontend/:/app"
       - "./frontend/node_modules:/app/node_modules"
     environment:
       - CHOKIDAR_USEPOLLING=true
