version: "3.8"
services:
  opskit-frontend:
    stdin_open: true
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    volumes:
#      - "./:/app"
  opskit-backend:
    stdin_open: true
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5057:5057"